{% set name = "stumpy" %}
{% set version = "1.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f29d3da980412150e7b029ab0cd8e7b132adcbf1c66ef7a4d35d564808bfba8a

build:
  number: 0
  # skip for s390x as numba is not available on that platform.
  skip: true  # [s390x or py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python
    - numpy >=1.21
    - scipy >=1.10
    - numba >=0.57.1
  run_constrained:
    - pandas >=0.20.0
    - dask-core >=1.2.2
    - distributed >=1.28.1
    - black >=22.1.0
    - isort >=5.11.0

test:
  source_files:
    - tests
    - pyproject.toml
  imports:
    - stumpy
  requires:
    - pip
    - pytest >=4.4.1
    - pandas
    - dask-core
    - distributed
  commands:
    - pip check
    #E AssertionError: Mismatched elements: 10 / 30 (33.3%)
    - pytest -v tests --deselect=tests/test_precision.py::test_snippets

about:
  home: https://github.com/TDAmeritrade/stumpy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: |
    A powerful and scalable library that can be used for a variety of time series data mining tasks.
  description: |
    STUMPY is a powerful and scalable Python library that computes something called a matrix profile,
    which can then be used for a variety of time series data mining tasks. It provides efficient algorithms
    for tasks such as similarity search, motif discovery, time series segmentation, and anomaly detection.
  doc_url: https://github.com/TDAmeritrade/stumpy/blob/master/README.rst
  dev_url: https://github.com/TDAmeritrade/stumpy

extra:
  recipe-maintainers:
    - seanlaw
