travis:
  secure:
    BINSTAR_TOKEN: jJ9Sm3eXkFnXDpxBknI0cvQWlqoXWa/dLrG3sDCgUZpJujteOMP1fJSXNSFrYeP9leSMJLi0Jc2c08I9X3HZh4UuYrCTGFO18cWxUM6Z3v+G/9+2MU5QsW27XKUa2ThPjVwaFqUMBCNrDQ9lRc4qkO/8Gi3PUd6QfRFOlOLh+GFIISsFD96eWLLvwFuW9mIVWkCmt9BjybL30qSFtIhO8QtlHau6ZxhEDftg7XVFg7nXhavFVm7tQcCr1GOuxR0GCUTwe/R5PRsl5IhWFsHDvF3WKHuWfHd0fjrGEc/NExlAZSHNGdVck7tAUt335ABi8ptn/mrN887ZiB1MfMBRKVKgGUVJfK+YIfg47fZngP6JnufJQ4Ya+VMdrMJqsg9HaZyM+xbsfhfhtDSpf5L8zJPhn2d/xPorASva/WqnbejCQU50FKUE3DYJzkAUgD+nOq03flTi9d6yFZtpuaC54iw8jHBp0/ZNn1yLaUfhuxcNwmmVDhgIcABHqCa/6Mky19XwgOEN5UwmYFCObDOIMWyX4Yka2aSZHh+YlMrL6saVS37yKnTvTz4xsH9BaEI7Gln8y/vyjmn6/6o+ULX5vYIII5nQtIs3uSEyiYbgLisXoLRgJ5LscDP99kyd25Gru9cNIqKpBXGhESz6QuAiyu+G5u3XRLSI/CnvEZpNOUw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
